### ISSUE TITLE
Вы можете выложить Dockerfile для ubuntu

### ISSUE THREAD

**Issue by deepdivenow** [lean-delivery/docker-systemd#2]
Вы можете выложить Dockerfile для ubuntu?

**Comment by vutkin** [comment]
@deepdivenow Hi, sure, please look in branches for this:
https://github.com/lean-delivery/docker-systemd/blob/ubuntu-18.04/Dockerfile

**Comment by deepdivenow** [comment]
Thanks!
I was looking bad.
